/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>
#include <sys/time.h>
/* Header for class com_stereo_ManualCalib_glutils_myGLUtils */

#ifndef _Included_com_stereo_ManualCalib_glutils_myGLUtils
#define _Included_com_stereo_ManualCalib_glutils_myGLUtils
#ifdef __cplusplus
extern "C" {
#endif

extern double gAngle;//gAngle = 17.78;
extern double pxwid ;//pxwid  = profile->gwidth;
extern int baseView;

void saveProfile();
void updateImage(int w,int h,float angle,float delts,float deltp);
void init(double angle,double gw,int w,int h);
void stop();
void readFrame();
long getTimeMs();
void saveFile();
void readFile();
void sendDelt(int n );
void autoSwitch();
int getd();
void mPiex(int x,int y);
#ifdef __cplusplus
}
#endif
#endif
